//Car.startEngine();
// Calculator cs = new Calculator(23, 95);
// cs.add();
// cs.multiply();

// Student st = new Student();
// st.age = 22;
// st.name = 'Brandon Wiggins';
// st.printDetails();

// Book bk = new Book('Basic Economics', 'Thomas Sowell');
// bk.printBooks();

// ClassB cb = new ClassB();
// cb.dislayMessage();

// OrderService os = new OrderService(5, 15.29);
// os.getTotal();

// Shape s = new Shape(10, 5);
// system.debug('Area is: ' + s.calculateArea());
MessagePrinter.printHello();
